prgrms-fe-devcourse/NFE1_2_3_Clogging

clogging/src/app/layout.tsx, clogging/src/app/page.tsx, clogging/src/app/style-guide/page.tsx, clogging/src/components/pages/home/HomeStyleWrapper.tsx, clogging/src/components/ui/Navigation.tsx, clogging/src/contexts/ThemeContext.tsx, clogging/src/providers/Providers.tsx, clogging/tailwind.config.ts
- 테마 모드 상태 관리
- 테마 모드 전역 관리 기능 추가
-
=> ✨ Feat: 테마 모드 전역 관리 기능 추가

clogging/src/app/home/page.tsx, clogging/src/components/post_card/PostCard.tsx, clogging/src/components/ui/common/Card.tsx
- 포스트 카드 디자인 구성하였습니다.
- 더미데이터로 출력이 잘 되는지 확인하였습니다.
- 디자인 부분을 우선 봐주셨으면 좋겠습니다! 혹시라도 tailwind 상으로 문제가 있는 부분이 있으면 말씀해주세요!
- 우선은 디자인 구성만 완료하였습니다.
- 추후 api가 완성되면, 해당 모델에 맞게 수정 후, 적용하도록 할 예정입니다!
=> ✨ Feat: 포스트 카드 제작

clogging/src/app/home/page.tsx
- 홈 화면 LNB 제작하였습니다!
- 최신 / 트렌딩으로 정렬할 수 있도록 하였습니다!
-
- 추후 마찬가지로 데이터 모델 및 API 구성되면, 해당 로직에 맞게 수정하겠습니다!
=> ✨ Feat: 홈 화면 LNB 제작

clogging/next.config.js, clogging/pnpm-lock.yaml, clogging/src/app/feed/page.tsx, clogging/src/components/HorizontalPostCard/HorizontalPostCard.tsx, clogging/src/components/PostCard/PostCard.tsx
- 피드 페이지에 들어갈 가로형 포스트 컴포넌트를 제작하였습니다.
- 클릭하면 해당 포스트 id를 가진 상세 페이지로 이동합니다.
-
- 요 카드 컴포넌트는 수빈님이 만들어두신 목 데이터 연동해서 제작하였습니다!
- 추후 api가 완성되면 다시 재 연결 해 놓겠습니다!
- 폴더 컨벤션 또한 조금 헷갈려서 기존 하던대로 진행하였습니다. 월요일날 저희 폴더 컨벤션 정해지면 책임지고 옮겨 놓겠습니다!
=> ✨[Feat] 포스트 가로 컴포넌트 제작

clogging/src/features/Category/hooks.ts, clogging/src/features/Post/types.ts, clogging/src/features/Post/ui/Detail/Content.tsx, clogging/src/features/Post/ui/Detail/Header.tsx, clogging/src/features/Post/ui/Detail/Navigation.tsx, clogging/src/features/Post/utils/elapsedTimeCalculation.tsx, clogging/src/mocks/data/posts.ts
- 포스트 본문 구현
- 포스트 목 데이터 모델에 이미지 프로퍼티 추가 및 categoryId 타입을 string 으로 변경
- close #21
-
=> ✨ Feat: 포스트 본문 구현

clogging/src/app/api/categories/create/route.ts, clogging/src/app/api/categories/delete/[id]/route.ts, clogging/src/app/api/categories/route.ts
- 카테고리 관련 API 를 구현해서 리뷰받아야 합니다!
- close #29 
- #### 모든 카테고리 조회 : 테스트로 3개 정도 만들어놓고 삭제를 해버리니 3번밖에 안 남았습니다.. DB에도 3번 카테고리 밖에 없어용
- #### 카테고리 생성 : 3번 카테고리를 생성할 때 테스트 결과입니다!
- #### 카테고리 삭제 : 파라미터로 해당하는 카테고리의 id 를 찾아 삭제합니다!
- 지금 졸려서 눈 반만 뜨고 작업중이라 저장이 되어야 하는 키 값이 빠져있는지 확인 부탁드립니당!
- new Date().toISOString() 로 년-월-일 시:분:초 로 카테고리를 생성한 시간을 표시해봤는데 어떠신가요?
보기 깔끔하다면 createdAt의 표기 방식(지금은 20241030 이런식으로만 표시함)으로 모두 바꿀지 고민중입니다,,,, 
> 상단에 설명과 함께 첨부함
=> Feat: 카테고리 API 구현하기

clogging/src/app/api/posts/[id]/route.ts
- 조회수랑 댓글수를 추가했는데 제대로 호출되는지 궁금합니다!
close #47 
- 각 포스트 id 별로 조회수(viewCount) 댓글수(commentCount) 필드 추가
- 포스트 날짜 표시하기 편하게 년 월 일 키 값 분리
- 태그는 아직 추가 안했습니다! 먼저 카운트 테스트할 API 올립니다!
=> Feat: 카운팅 구현하기 

clogging/src/app/(auth)/admin/category/page.tsx, clogging/src/app/api/categories/create/route.ts, clogging/src/app/api/categories/reorder/route.ts, clogging/src/app/api/categories/update/[id]/route.ts, clogging/src/features/Category/hooks.ts, clogging/src/features/Category/types.ts, clogging/src/features/Category/ui/admin/CategoryForm.tsx, clogging/src/features/Category/ui/admin/CategoryItem.tsx, clogging/src/features/Category/ui/admin/CategoryList.tsx, clogging/src/features/Category/ui/admin/CategoryManagement.tsx, clogging/src/features/Category/ui/admin/CategoryOrderList.tsx
#56 
- 카테고리 추가, 삭제
- 카테고리 업데이트
- app/api/categories 에 조금 추가했습니다.
- 추후 시간되면 카테고리 이름 수정 기능 구현 예졍입니당..
=> Feat: admin 카테고리 관리 데이터 연동

clogging/src/app/(auth)/admin/category/page.tsx, clogging/src/features/Category/hooks.ts, clogging/src/features/Category/ui/admin/CategoryForm.tsx, clogging/src/features/Category/ui/admin/CategoryManagement.tsx, clogging/src/features/Category/ui/admin/CategoryOrderList.tsx
> 해결하려는 문제가 무엇인가요 ? 
- 카테고리 추가 시 2번 추가되는 오류 발견해서 수정했습니다.
- 카테고리 추가 시 2번 추가되는 오류 수정
- 카테고리 같은 이름 입력 시  alert 추가했습니다.
- 추가 후 페이지에 반영되도록 수정
-
=> 🐛 Fix :  카테고리 추가 오류, 순서변경 오류 수정

clogging/next.config.js, clogging/src/features/Post/ui/Detail/Content.tsx, clogging/src/features/Post/ui/Detail/index.tsx, clogging/src/features/Post/ui/TableOfContents.tsx
- 본문 목차 확인 및 이동 기능 추가
- close #24 
- 본문 목차 확인 및 이동
https://github.com/user-attachments/assets/2e721138-496b-46b2-a8b8-f0a0f596cf3e
=> ✨ Feat: 게시물 상세 페이지 본문에 목차 확인 및 이동 기능 추가

clogging/src/app/api/search/route.ts, clogging/src/app/search/page.tsx, clogging/src/features/Search/hooks.ts, clogging/src/shared/ui/Form/SearchBar.tsx
- 검색 페이지를 구현하였습니다.
- 제목 혹은 본문에 단어가 포함되면 검색 후, 포스트 카드 형태로 나타납니다.
- 해당 포스트 카드를 누르면 상세 페이지로 바로 이동할 수 있습니다.
-
- 아쉽게도 firebase 특성 상 기본적으로 전체 단어나 문자열의 시작 부분만 검색할 수 있고, 중간이나 끝부분의 부분 문자열 검색은 지원하지 않는다고 합니다.
=> Feat: 검색 페이지 구현

clogging/src/app/api/comments/create/route.ts, clogging/src/app/api/comments/replies/create/route.ts, clogging/src/app/api/comments/replies/update/route.ts, clogging/src/app/api/comments/update/route.ts, clogging/src/features/Comment/api/Reply/replyApi.ts, clogging/src/features/Comment/api/Reply/useReply.ts, clogging/src/features/Comment/api/commentApi.ts, clogging/src/features/Comment/api/useComments.ts, clogging/src/features/Comment/lib/stores/useCommentFormStore.ts, clogging/src/features/Comment/ui/CommentForm.tsx, clogging/src/features/Comment/ui/CommentItem.tsx, clogging/src/features/Comment/ui/CommentList.tsx, clogging/src/features/Comment/ui/InputComment.tsx
- 유저 상태에 따른 댓글 비공개 처리
- 댓글, 답글 데이터 모델에 isPrivate 필드 추가
- 댓글, 답글의 생성, 수정 요청 응답 로직 수정
- close #73 
- 
=> ✨ Feat: 유저 상태에 따른 댓글 비공개 처리 [#73]

clogging/src/app/(admin)/admin/init/layout.tsx, clogging/src/app/(admin)/admin/init/page.tsx, clogging/src/app/(auth)/admin/admin-settings/page.tsx, clogging/src/app/(auth)/admin/layout.tsx, clogging/src/app/ClientLayout.tsx, clogging/src/app/api/admin/init/route.ts, clogging/src/app/api/admin/password/route.ts, clogging/src/app/api/admin/reset/route.ts, clogging/src/app/api/admin/route.ts, clogging/src/app/api/admin/update-password/route.ts, clogging/src/app/api/admin/verify/route.ts, clogging/src/app/layout.tsx, clogging/src/app/page.tsx, clogging/src/features/Admin/Blog-settings/ui/SettingPassword.tsx, clogging/src/features/Admin/api/adminApi.ts, clogging/src/features/Admin/hooks/useAuth.ts, clogging/src/features/Admin/stores/useAdminStore.ts, clogging/src/features/Admin/ui/AdminAuth.tsx, clogging/src/shared/ui/layout/Navigation.tsx
- 폴더, 파일 새로 작업해서 merge 가능합니다!
- 관리자 비밀번호 설정 및 관리 기능 추가
- /admin/init 페이지에서 최초 비밀번호 설정 가능
- 설정되지 않은 경우 자동으로 초기 설정 페이지로 리다이렉트
- 초기 비밀번호 값은 INITIAL_PASSWORD 변수에 설정
- /admin/settings 페이지에서 비밀번호 변경이 가능
- close #76 
-
=> Feat: 관리자 비밀번호 설정 및 관리 기능 추가

clogging/src/app/posts/page.tsx, clogging/src/features/Profile/ui/Section.tsx
- 관리자 페이지에서 배너, 프로필, 소개 등 수정사항이 제대로 변경되는 것을 확인했습니다.
- Post Page에 배너 사진이 연동되도록 구현하였습니다.
- Home Page에 프로필사진, 제목, 소개가 연동되도록 구현하였습니다.
-
- 선영님이 만들어주신 코드 자체를 그대로 적용했을 때 정상적으로 오류 발생하지 않고 데이터 연동되는 것 확인했습니다!
=> Feat: 관리 페이지 배너, 이미지 등 저장상태 확인 및 홈 ,피드 페이지에 연결

clogging/src/app/(auth)/admin/comment/page.tsx, clogging/src/app/(auth)/admin/page.tsx, clogging/src/features/Admin/Analytics/hooks/getBlogData.ts, clogging/src/features/Admin/Analytics/types.ts, clogging/src/features/Admin/Analytics/ui/BlogDataCard.tsx, clogging/src/features/Admin/Analytics/ui/BlogDataList.tsx, clogging/src/features/Admin/Dashboard/ui/BlogDataSection.tsx, clogging/src/features/Admin/Dashboard/ui/CommentSection.tsx, clogging/src/features/Admin/Dashboard/ui/LoadingError.tsx, clogging/src/features/Admin/Dashboard/ui/PostListSection.tsx, clogging/src/features/Comment/ui/admin/CommentItem.tsx, clogging/src/features/Comment/ui/admin/CommentList.tsx
- 메인 대시보드 구현
- 메인 대시보드 레이아웃
- 최근 포스트 컴포넌트
-
=> Feat:admin  메인대시보드

clogging/src/app/posts/page.tsx, clogging/src/features/Category/ui/CategorySection.tsx, clogging/src/features/Comment/api/useCommentCount.ts, clogging/src/features/Post/types.ts, clogging/src/features/Post/ui/Card/HorizontalPostCard.tsx, clogging/src/features/Post/ui/Card/PostCard.tsx
- 런타임 에러가 발생하지 않게 수정하였습니다.
- 가로형 컴포넌트에 실제 저장된 카테고리가 나오도록 수정하였습니다.
- 카테고리 섹션에서 해당 카테고리가 적용된 포스트의 수를 확인할 수 있습니다.
- 카테고리 별로 실제 필터링 되도록 수정하였습니다.
-
=> Fix: 런타임 에러 및 카테고리 연동 수정

clogging/src/app/(auth)/admin/analytics/page.tsx, clogging/src/app/(auth)/admin/page.tsx, clogging/src/features/Admin/Analytics/types.ts, clogging/src/features/Admin/Analytics/utils/getBlogData.ts, clogging/src/features/Admin/Dashboard/utils/getRecentPosts.ts
#88 
- 메인대시보드에 통계  페이지 데이터 추가해서 쓰면서 오류 발생
- 데이터 가져오는 함수 분리 및 수정
-
- 메인 대시보드에 데이터 새로 추가하면서 데이터 형식 수정하지 않아서, 날짜형식떄문에 생긴 문제였습니다.
=> 🐛 Fix :  블로그 통계 데이터 오류 수정

clogging/src/features/Post/ui/Detail/Header.tsx
- 카테고리를 실제 DB의 포스트에 저장된 값으로 들고 올 수 있도록 수정하였습니다.
-
=> 🐛 Fix: 상세 페이지에 카테고리 실제로 적용되도록 수정

clogging/src/app/(auth)/posts/[id]/edit/page.tsx, clogging/src/app/api/posts/update/route.ts, clogging/src/app/api/tags/check/route.ts, clogging/src/features/Post/api/postApi.ts, clogging/src/features/Post/ui/Detail/Content.tsx, clogging/src/features/Post/ui/Detail/Header.tsx, clogging/src/features/Post/ui/edit/EditPostEditor.tsx
게시물 생성에서 오류나서 관련 코드는 원복해서 올립니다
- 게시물 수정, 삭제 작업중
- 게시물 생성쪽 오류나서 관련 파일 원복해서 올림
-
=> ✨ Feat: 게시물 수정, 삭제 작업중

clogging/src/features/Post/ui/Detail/Content.tsx
- 없습니다!
- close #93 
- 상세포스팅에도 마크다운 서식 적용시키기
- 포스팅 등록했을 때 정상적으로 마크다운서식으로 작성하신 게시물로 보이는지 확인해주세용!
=> Feat: 상세 포스팅 마크다운 적용 #93

clogging/src/app/(auth)/admin/blog-settings/page.tsx, clogging/src/app/layout.tsx, clogging/src/features/Admin/Blog-settings/constants.ts, clogging/src/features/Admin/Blog-settings/hooks/getFaviconUrl.ts, clogging/src/features/Admin/Blog-settings/hooks/useFetchSettings.ts, clogging/src/features/Admin/Blog-settings/hooks/useImageHandling.ts, clogging/src/features/Admin/Blog-settings/types.ts, clogging/src/features/Admin/Blog-settings/ui/FaviconImageField.tsx, clogging/src/features/Admin/Blog-settings/ui/ProfileImageField.tsx, clogging/src/features/Admin/Blog-settings/ui/SettingTextField.tsx, clogging/src/features/Admin/Blog-settings/ui/SettingsDisplay.tsx, clogging/src/features/Admin/Blog-settings/ui/SettingsForm.tsx, clogging/src/features/Admin/Blog-settings/ui/bannerImageField.tsx
#86 
-  등록된 이미지 미리보기
-  기존 이미지파일 제거
- 블로그 관리 ui 수정
- 블로그 관리 페이지 이미지 제거 기능
- default 이미지 설정
- 파비콘 변경 적용
- 이미지 등록 잘 되는지 확인해주시면 좋습니당~
=> Fix: 블로그 관리 ui 수정

clogging/src/app/posts/page.tsx, clogging/src/features/Post/ui/Card/HorizontalPostCard.tsx, clogging/src/features/Tag/hooks.ts
- 피드 페이지 반응형 수정 하였습니다.
- 태그 로직도 조금 수정하여 최대 3줄 보이도록 설정하였습니다.
-
=> Fix: 피드 페이지 태그 로직 수정 및 반응형 구현

clogging/src/features/Post/lib/hooks/usePostEditor.ts, clogging/src/features/Post/ui/Detail/Content.tsx, clogging/src/features/Post/ui/Posting/PostEditor.tsx, clogging/src/features/Post/ui/edit/EditPostEditor.tsx
- 마크다운 미리보기에 이미지가 안 보이는 이슈가 있었습니다 !
- 상세 포스팅 페이지에 이미지가 중복되는 이슈가 있었습니다!
- close #94 
- 마크다운 미리보기에 이미지 보이게 구현
- 이미지 마크다운 태그 적용 구현
- 상세 포스팅 페이지의 이미지 중복 렌더링 해결 
- 포스팅을 등록했을 때에 이미지가 중복되는게 있는지 확인해주세요!
- 여러장의 이미지 추가 가능한지 확인해주세요!
- 포스팅 수정할 때에 이미지 추가하면 미리보기에 이미지가 보이는지 확인해주세요!
- 포스팅 작성과 수정 모두 이미지 넣어서 테스트 부탁드립니다!
=> Fix: 포스팅 이미지 모든 이슈 해결하기

clogging/src/app/(admin)/admin/init/page.tsx, clogging/src/app/(auth)/admin/category/page.tsx, clogging/src/app/(auth)/admin/comment/page.tsx, clogging/src/app/ClientLayout.tsx, clogging/src/app/home/page.tsx, clogging/src/app/posts/[id]/page.tsx, clogging/src/app/posts/page.tsx, clogging/src/app/search/page.tsx, clogging/src/features/Category/ui/admin/CategoryManagement.tsx, clogging/src/features/Post/ui/Detail/index.tsx, clogging/src/features/Post/ui/Posting/PostEditor.tsx, clogging/src/features/Post/ui/edit/EditPostEditor.tsx
=> ✨ Feat: 로딩 애니메이션 추가"

clogging/package.json, clogging/pnpm-lock.yaml, clogging/src/features/Post/ui/Detail/Content.tsx, clogging/src/features/Post/ui/Posting/PostEditor.tsx, clogging/src/features/Post/ui/edit/EditPostEditor.tsx
- 포스트 작성할 때 엔터키 횟수에 따라 줄바뀜이 이상하게 나오던 버그를 해결 했습니다.
- close #116 
- 포스트 작성, 수정 줄 바꿈 버그 수정
- 상세포스팅 화면에서도 적용
- 작성, 수정할 때 엔터키 한 번만으로 줄바꿈이 적용되는지 확인해주세요!
- 상세포스팅에도 줄바꿈 했던게 그대로 적용되었는지 확인해주세요!
- remark-breaks 설치했습니다. pnpm i 부탁드려용
- 마지막 PR 입니다 ㅎㅎ 고생많으셨습니다 여러분 <3
=> Fix: 줄바꿈 테스트 #116
